version: "3"
services:
  database:
    image: mongo:6.0.4
    environment:
      - MONGO_INITDB_DATABASE=Receipts
    volumes:
      - "./db_data:/data/db"
    ports:
      - "27017:27017"

  server:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://database:27017/Receipts

  client:
    build: ./frontend
    depends_on:
      - server
      - database
    ports:
      - "3003:3003"

